### ISSUE TITLE
Please update the readme to make aware all the libraries one has to use to follow the instructions

### ISSUE THREAD

**Issue by lennykey** [hiddewie/money-kotlin#2]
// Create a monetary amount of a specific type and currency

`
val money = (10.0).ofCurrency<FastMoney>("EUR")
`

The example shown in the README can not be used out of the box. I also had to include e.g.
`
    implementation("org.javamoney:moneta-bp:1.4.1")
`
to make it work.

First I was confused if I am making something wrong. Could you please clarify what is needed to use the extensions in this library or even better provide all the needed libraries within your library

**Comment by hiddewie** [comment]
It is mentioned in the readme:

> This code builds upon the Money API of the JSR proposal, not the [Moneta classes](https://github.com/JavaMoney/jsr354-ri#readme) in the reference implementation.

So this library only adds methods on top of the API, and does not depend on a specific implementation. If you like to use a specific implementation, such as the reference implementation Moneta, you may of course use this by adding the implementation as a dependency.

I will make this a bit more clear in the readme.
